name: ERA5 Download

on:
  # push:
  #   branches:
  #     - "main"
  # cron schedules are in UTC
  # running at 6 am pst, which translates to 2 pm utc.
  schedule:
    - cron: '30 15 * * 0-2'
  workflow_dispatch:
  repository_dispatch:
    types: run-era5-download

jobs:
  bias_correct:
    defaults:
      run:
        shell: bash
    name: 'Download ERA5'
    runs-on: ubuntu-22.04
    environment: RUN
    env:
      OBJ_STORE_BUCKET: ${{ secrets.OBJ_STORE_BUCKET }}
      OBJ_STORE_SECRET: ${{ secrets.OBJ_STORE_SECRET }}
      OBJ_STORE_USER: ${{ secrets.OBJ_STORE_USER }}
      OBJ_STORE_HOST: ${{ secrets.OBJ_STORE_HOST }}
      ECMWF_DATASTORES_URL: ${{ secrets.ECMWF_DATASTORES_URL }}
      ECMWF_DATASTORES_KEY: ${{ secrets.ECMWF_DATASTORES_KEY }}

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
       fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - id: install_dependencies
      name: install python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install -r scripts/src/requirements_era5.txt

    - id: era5_download
      name: Download ERA5 data
      shell: bash
      run: |
        python scripts/src/main_ERA5.py
